### ISSUE TITLE
out-of-date clone because ?

### ISSUE THREAD

**Issue by igouy** [lemire/ComputerLanguageBenchmark#1]
Hi

Surprisingly I chose to do the work  required to continue the benchmarks game after debian/alioth EOL.

I found this out-of-date clone because you are being credited: 

I. Gouy, D. Lemire, The Computer Language Benchmarks Game, (2021). https://github.com/lemire/ComputerLanguageBenchmark (accessed December 16, 2022).

"Software Energy Efficiency? A Survey of Software Industry Developers."

https://doi.org/10.1016/j.procs.2024.09.589

best wishes Isaac

**Comment by lemire** [comment]
Can you elaborate? I am not sure what the issue you are reporting is?

**Comment by lemire** [comment]
Note that I have nothing to do with https://doi.org/10.1016/j.procs.2024.09.589 (to my knowledge)

**Comment by igouy** [comment]
The author of https://doi.org/10.1016/j.procs.2024.09.589 is confused by your 6 year old fork/clone of the old benchmarks game.

They think your fork/clone is the benchmarks game and you have something to do with the project.

Actually all the code you were trying to protect was archived before I moved the website --

    https://salsa.debian.org/benchmarksgame-team/archive-alioth-benchmarksgame


Could you at-least update your fork/clone.

**Comment by lemire** [comment]
synced.
